output/unpackaged/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>Type of partner company.</description>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

output/unpackaged/unpackaged/objects/Partner_Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Current review status of the partner application.</description>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country where the prospective partner is based.</description>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Tier__c</fullName>
        <description>Partner tier requested by the applicant.</description>
        <label>Requested Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Application</label>
    <nameField>
        <label>Partner Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

output/unpackaged/unpackaged/objects/Partner_Document__c.object
<CustomObject>
    <fields>
        <fullName>Onboarding__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Onboarding</label>
        <referenceTo>Partner_Onboarding__c</referenceTo>
        <relationshipLabel>Submitted Documents</relationshipLabel>
        <relationshipName>Submitted_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Replacement Required</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <label>Version Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Document</label>
    <nameField>
        <displayFormat>PDOC-{000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

output/unpackaged/unpackaged/objects/Partner_Document_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Onboarding__c</fullName>
        <label>Onboarding</label>
        <referenceTo>Partner_Onboarding__c</referenceTo>
        <relationshipLabel>Document Requirements</relationshipLabel>
        <relationshipName>Document_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Submission</fullName>
                    <default>true</default>
                    <label>Awaiting Submission</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Replacement Required</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Document Requirement</label>
    <nameField>
        <displayFormat>PDR-{000000}</displayFormat>
        <label>Requirement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Document Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

output/unpackaged/unpackaged/objects/Partner_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Gate_Status__c</fullName>
        <label>Activation Gate Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                    <default>true</default>
                    <label>Blocked</label>
                </value>
                <value>
                    <fullName>Evaluating</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Released By Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Partner_Application__c</referenceTo>
        <relationshipLabel>Onboarding Cases</relationshipLabel>
        <relationshipName>Onboarding_Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Stage__c</fullName>
        <label>Current Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification</fullName>
                    <default>true</default>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Evidence</fullName>
                </value>
                <value>
                    <fullName>Due Diligence</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Account Establishment</fullName>
                </value>
                <value>
                    <fullName>Partner Enablement</fullName>
                </value>
                <value>
                    <fullName>Provisioning</fullName>
                </value>
                <value>
                    <fullName>Readiness</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Onboarding_Key__c</fullName>
        <externalId>true</externalId>
        <label>Onboarding Key</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Onboardings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Onboarding</fullName>
                    <default>true</default>
                    <label>Onboarding</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Under Investigation</fullName>
                </value>
                <value>
                    <fullName>Termination Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version Number</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Onboarding</label>
    <nameField>
        <displayFormat>PON-{000000}</displayFormat>
        <label>Onboarding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Onboardings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

output/unpackaged/unpackaged/classes/PartnerDocumentReviewControllerTest.cls
@IsTest
private class PartnerDocumentReviewControllerTest {
  @IsTest
  static void getReviewQueueReturnsRowsForAuthorizedReviewer() {
    Partner_Onboarding__c onboarding = onboarding();
    PartnerDocumentService.generateRequirements(onboarding.Id);
    Partner_Document_Requirement__c requirement = [
      SELECT Id
      FROM Partner_Document_Requirement__c
      WHERE Onboarding__c = :onboarding.Id
      LIMIT 1
    ];
    PartnerDocumentService.submitDocument(
      requirement.Id,
      '069000000000011AAA',
      'upload-011',
      null
    );

    User reviewer = reviewerUser();
    System.runAs(reviewer) {
      List<PartnerDocumentReviewListDTO> queue = PartnerDocumentReviewController.getReviewQueue();
      Assert.areEqual(1, queue.size());
      Assert.isNotNull(queue[0].partnerName);
      Assert.areEqual('Submitted', queue[0].status);
    }
  }

  @IsTest
  static void getReviewQueueThrowsForUnauthorizedUser() {
    Partner_Onboarding__c onboarding = onboarding();
    PartnerDocumentService.generateRequirements(onboarding.Id);

    User unpermissioned = TestUserFactory.createInternalUser();
    System.runAs(unpermissioned) {
      try {
        PartnerDocumentReviewController.getReviewQueue();
        Assert.fail('Expected document review permission guard.');
      } catch (AuraHandledException expected) {
        Assert.isTrue(expected.getMessage().contains('permission'));
      }
    }
  }

  @IsTest
  static void reviewDocumentDelegatesToServiceAndUpdatesStatus() {
    Partner_Onboarding__c onboarding = onboarding();
    PartnerDocumentService.generateRequirements(onboarding.Id);
    Partner_Document_Requirement__c requirement = [
      SELECT Id
      FROM Partner_Document_Requirement__c
      WHERE Onboarding__c = :onboarding.Id
      LIMIT 1
    ];
    Partner_Document__c document = PartnerDocumentService.submitDocument(
      requirement.Id,
      '069000000000012AAA',
      'upload-012',
      null
    );

    User reviewer = reviewerUser();
    System.runAs(reviewer) {
      PartnerDocumentReviewDecisionDTO request = new PartnerDocumentReviewDecisionDTO();
      request.documentId = document.Id;
      request.outcome = 'Accepted';
      PartnerDocumentReviewController.reviewDocument(request);
    }

    Assert.areEqual(
      'Accepted',
      [SELECT Status__c FROM Partner_Document__c WHERE Id = :document.Id]
      .Status__c
    );
  }

  private static Partner_Onboarding__c onboarding() {
    Account partnerAccount = PartnerSyncTestDataFactory.partnerAccount(
      'Document Controller Partner'
    );
    insert partnerAccount;
    Partner_Application__c application = new Partner_Application__c(
      Name = 'Document Controller Applicant',
      Company_Name__c = 'Document Controller Applicant',
      Business_Email__c = 'document-controller-' +
        System.now().getTime() +
        '@example.com',
      Application_Status__c = 'Approved',
      Requested_Tier__c = 'Gold',
      Partner_Type__c = 'Reseller',
      Country__c = 'Australia'
    );
    insert application;
    Partner_Onboarding__c onboarding = new Partner_Onboarding__c(
      Application__c = application.Id,
      Onboarding_Key__c = String.valueOf(application.Id),
      Partner_Account__c = partnerAccount.Id,
      Status__c = 'Onboarding',
      Current_Stage__c = 'Evidence',
      Activation_Gate_Status__c = 'Blocked',
      Version_Number__c = 1
    );
    insert onboarding;
    return onboarding;
  }

  private static User reviewerUser() {
    User reviewer = TestUserFactory.createInternalUser();
    TestUserFactory.assignPermissionSet(
      reviewer.Id,
      'PartnerSync_Internal_Admin'
    );
    return reviewer;
  }
}