output/unpackaged/unpackaged/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Partner_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

output/unpackaged/unpackaged/objects/Lead_Distribution_Log__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead processed by the distribution rule.</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Distribution_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner account selected for the lead assignment.</description>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Distribution_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Lead_Distribution_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Performed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Performed_Lead_Distribution_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Performed_On__c</fullName>
        <label>Performed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Distribution Log</label>
    <nameField>
        <label>Lead Distribution Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Distribution Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadDistributionLogService.cls
public with sharing class LeadDistributionLogService {
  public static void logAction(
    Id leadId,
    Id partnerAccountId,
    Id partnerContactId,
    String action,
    String status,
    String notes
  ) {
    if (!Schema.sObjectType.Lead_Distribution_Log__c.isCreateable()) {
      LoggingService.warn(
        'LeadDistributionLogService',
        'Skipping lead distribution log because user lacks create access.'
      );
      return;
    }

    try {
      Lead_Distribution_Log__c log = new Lead_Distribution_Log__c();
      log.Lead__c = leadId;
      log.Partner_Account__c = partnerAccountId;
      log.Partner_Contact__c = partnerContactId;
      log.Action__c = action;
      log.Status__c = status;
      log.Notes__c = notes;
      log.Performed_By__c = UserInfo.getUserId();
      log.Performed_On__c = System.now();

      insert SecurityUtil.stripForCreate(new List<SObject>{ log });
    } catch (Exception ex) {
      LoggingService.error(
        'LeadDistributionLogService',
        'Unable to create lead distribution log.',
        ex
      );
    }
  }
}