output/unpackaged/unpackaged/objects/Partner_Content__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Deck</fullName>
                </value>
                <value>
                    <fullName>Product Sheet</fullName>
                </value>
                <value>
                    <fullName>Pricing Guide</fullName>
                </value>
                <value>
                    <fullName>Marketing Asset</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Case Study</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Content</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Content</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

output/unpackaged/unpackaged/classes/PartnerContentCategoryDTO.cls
/**
 * Label/value pair for a Partner_Content__c Category__c picklist entry,
 * sent to the LWC layer to populate category filter options.
 */
public with sharing class PartnerContentCategoryDTO {
  /**
   * Display label of the picklist entry.
   */
  @AuraEnabled
  public String label { get; set; }
  /**
   * API value of the picklist entry.
   */
  @AuraEnabled
  public String value { get; set; }
}