output/unpackaged/unpackaged/objects/Partner_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Action_Label__c</fullName>
        <label>Action Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_URL__c</fullName>
        <label>Action URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Is_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Short title displayed for the notification.</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Partner Notification</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Partner Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/notifications/NotificationQueryService.cls
public with sharing class NotificationQueryService {
  public static List<PartnerNotificationDTO> getMyNotifications() {
    Id userId = UserInfo.getUserId();

    List<PartnerNotificationDTO> results = new List<PartnerNotificationDTO>();

    for (
      Partner_Notification__c row : NotificationSelector.selectMyActiveNotifications(
        userId
      )
    ) {
      PartnerNotificationDTO dto = new PartnerNotificationDTO();

      dto.notificationId = row.Id;
      dto.title = row.Title__c;
      dto.message = row.Message__c;
      dto.actionLabel = row.Action_Label__c;
      dto.actionUrl = row.Action_URL__c;
      dto.priority = row.Priority__c;
      dto.isRead = row.Is_Read__c;
      dto.createdDate = row.CreatedDate;

      results.add(dto);
    }

    return results;
  }

  public static Integer getUnreadCount() {
    return NotificationSelector.countUnreadForUser(UserInfo.getUserId());
  }
}